### ISSUE TITLE
Can't compile and run for iOS project using version 1.0.4

### ISSUE THREAD

**Issue by celsoperezcruz** [FMarcelFC/device_session_id#1]
# Can't compile and run for iOS project using version 1.0.4 in Android works fine.

This is my xcode build ouput:

Error output from Xcode build:
↳
    2022-08-10 01:08:55.290 xcodebuild[70843:450092] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    2022-08-10 01:08:55.291 xcodebuild[70843:450092] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    ** BUILD FAILED **
Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/z4/xms6c_k12r3f869ssq9_gvtr0000gn/T/flutter_tools.MP7MuU/flutter_ios_build_temp_dire20Zz4/temporary_xcresult_bundle
    remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
/Users/../.pub-cache/hosted/pub.dartlang.org/device_session_id-1.0.4/ios/Classes/SwiftDeviceSessionIdPlugin.swift:3:8: error: error extracting version from module interface
    import OpenpayKit
           ^
    /Users/../Work/Gruppi/GruppiApp/gruppiapp/build/ios/Debug-dev-iphoneos/XCFrameworkIntermediates/device_session_id/OpenpayKit.framework/Modules/OpenpayKit.swiftmodule/arm64-apple-ios.swiftinterface:1:1: error: error extracting version from module interface
    // swift-interface-format-version: 1.0
    ^
/Users/../.pub-cache/hosted/pub.dartlang.org/device_session_id-1.0.4/ios/Classes/SwiftDeviceSessionIdPlugin.swift:13:20: error: cannot find type 'Openpay' in scope
          var openpay: Openpay!
                       ^~~~~~~
/Users/../.pub-cache/hosted/pub.dartlang.org/device_session_id-1.0.4/ios/Classes/SwiftDeviceSessionIdPlugin.swift:21:17: error: cannot find 'Openpay' in scope
          openpay = Openpay(withMerchantId: MERCHANT_ID ?? "", andApiKey: API_KEY ?? "", isProductionMode: productionMode ?? false, isDebug: false)
                    ^~~~~~~

Command CompileSwiftSources failed with a nonzero exit code
    remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
    Command CompileSwiftSources failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    Result bundle written to path:
    	/var/folders/z4/xms6c_k12r3f869ssq9_gvtr0000gn/T/flutter_tools.MP7MuU/flutter_ios_build_temp_dire20Zz4/temporary_xcresult_bundle

Can help please!

**Comment by FMarcelFC** [comment]
It seems like an error with the new version of Xcode and the Swift version of the Openpay library, currently working on fixing it.

**Comment by FMarcelFC** [comment]
@celsoperezcruz Hello again! I have released a new version of the project that implements the Openpay sdk via Cooapods. It appears that it solved the problem you describe, if you could test it and give me your output it would be of great help, thank you! The new version is device_session_id: ^1.0.6
